/**
 * The runtime's own words.
 *
 * Not the app's content — that comes from the manifest, in whatever language it
 * was written. These are the handful of things the runtime says on its own
 * behalf: an empty table, a search box, the count of what did not fit.
 *
 * They lived as hardcoded English in five components and as four separate
 * word-maps in four others, so a Spanish app told its user "No related
 * records." and an English one had a menu labelled "Menú" depending on which
 * component was speaking. One place, keyed by the APP's locale rather than the
 * platform session's: an app is read by its users, who did not choose the
 * language of the person who built it.
 *
 * English is the fallback for a language not listed, which is a choice about
 * being readable rather than about being right — a missing translation should
 * degrade to a word, not to a key.
 */
type Dict = Record<string, string>;

const WORDS: Record<string, Dict> = {
    en: {
        columns: 'Columns',
        search: 'Search…',
        no_matches: 'No row matches',
        of_loaded: 'among the first {n} of {total}',
        showing_of: 'Showing {n} of {total}',
        no_records: 'Nothing here yet.',
        no_related: 'Nothing linked to this record yet.',
        no_data: 'Nothing to plot.',
        menu: 'Menu',
        step_of: 'Step {n} of {total}',
        load_failed: 'This section could not be loaded',
        retry: 'Try again',
        picker_search: 'Search a record…',
        picker_none: 'No record matches',
        picker_more: 'Keep typing to narrow it down',
        picker_clear: 'Clear',
        picker_unavailable: 'Not available here',
        filter_all: 'All',
        range_today: 'Today',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Year',
        range_all: 'All time',
        range_all_label: 'the whole history',
        cancel: 'Cancel',
        confirm: 'Confirm',
        delete: 'Delete',
        thin_series: 'Not enough history yet to show a trend.',
        activity: 'Activity',
        leave_a_note: 'Leave a note…',
        comment_send: 'Comment',
        no_activity: 'Nothing has happened here yet.',
        by_the_app: 'The app',
        event_created: 'created it',
        event_updated: 'changed it',
        event_deleted: 'deleted it',
        event_restored: 'restored it',
        event_purged: 'deleted it for good',
        event_comment: 'wrote',
        bool_yes: 'Yes',
        bool_no: 'No',
        demo_banner: 'Demo environment',
        demo_explains: 'Nothing here is real data.',
        demo_leave: 'Back to production',
        demo_enter: 'Open the demo',
        demo_reset: 'Empty it',
        demo_reset_sure: 'Delete every demo record?',
        demo_seed: 'Fill it with samples',
        bulk_selected: '{n} selected',
        bulk_set: 'Set {f}…',
        bulk_delete: 'Delete',
        bulk_delete_title: 'Delete {n} records?',
        bulk_delete_message: 'They go for everyone, and this cannot be undone.',
        bulk_done: '{n} changed, {skipped} skipped.',
        bulk_removed: '{n} deleted, {skipped} skipped.',
        file_upload: 'Click to upload',
        file_uploading: 'Uploading {n}%…',
        file_take_photo: 'Take a photo',
        file_photo_hint: 'Opens the camera on a phone',
        signature_hint: 'Sign with your finger or the mouse',
        signature_clear: 'Clear',
        signature_accept: 'Use this signature',
        signature_saved: 'Signed',
        scan_button: 'Scan',
        scan_aim: 'Point the camera at the barcode',
        scan_close: 'Close the scanner',
        scan_no_camera: 'No camera available. Type the code instead.',
        scan_unsupported:
            'This browser cannot read barcodes. Type the code instead.',
        scan_captured: 'Scanned',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Use my location',
        geo_locating: 'Locating…',
        geo_denied:
            'Could not get your location. Type the coordinates instead.',
        geo_unavailable:
            'This device cannot locate itself. Type the coordinates instead.',
        geo_pick: 'Pick on a map',
        geo_pick_hint: 'Tap the map, then drag the pin to adjust',
        geo_pick_accept: 'Use this point',
        fill_from_document: 'Fill from a photo or PDF',
        fill_reading: 'Reading…',
        fill_failed: 'That document could not be read. Fill the form by hand.',
        fill_nothing: 'Nothing could be read from it. Fill the form by hand.',
        fill_check: 'Check every value before saving.',
        fill_from_voice: 'Dictate it',
        voice_hint: 'Tap to record, then say what goes in the form',
        voice_listening: 'Listening… tap to stop',
        voice_no_mic: 'No microphone available. Fill the form by hand.',
        voice_heard: 'Heard: {text}',
        share_copied: 'Link copied — paste it wherever you like.',
        share_failed: 'This could not be shared from this device.',
        copy_done: 'Copied',
        copy_failed: 'Could not copy. Select the text and copy it by hand.',
        scan_torch: 'Light',
        scale_button: 'Weigh',
        identity_refused:
            'This needs to be confirmed on your device. Nothing was saved.',
        scale_reading: 'Reading…',
        scale_failed: 'No reading from the scale. Type the number instead.',
        geo_auto_note: 'Location taken when this form opened.',
        nfc_button: 'Read a tag',
        nfc_hold: 'Hold the phone against the tag',
        nfc_close: 'Stop reading',
        nfc_unsupported:
            'This device cannot read NFC tags. Type the code instead.',
        nfc_denied: 'NFC is off or was refused. Type the code instead.',
        nfc_empty: 'That tag carries nothing readable.',
        nfc_failed: 'That tag could not be read. Try again, or type the code.',
        contact_button: 'From my contacts',
        dictate_button: 'Dictate',
        dictate_listening: 'Listening…',
        camera_aim: 'Frame the photo',
        camera_stamp_hint: 'The photo will carry the date, time and place',
        camera_close: 'Close the camera',
        camera_shoot: 'Take it',
        camera_retake: 'Take another',
        camera_use: 'Use this photo',
        camera_denied: 'No camera available. Attach a file instead.',
        camera_failed: 'That photo could not be saved. Try again.',
        screenshot_take: 'Capture the screen',
        screenshot_waiting: 'Choose what to share…',
        screenshot_hint: 'You choose which window is captured',
        ask_placeholder: 'Ask in your own words…',
        ask_showing: 'Showing: {q}',
        ask_not_understood:
            'That question could not be turned into a filter, so this is the whole list: {q}',
        ask_clear: 'Clear',
        presence_here: '{who} has this open too',
        form_send: 'Send',
        form_sending: 'Sending…',
        form_thanks: 'Thank you — your answers have been recorded.',
        form_already_answered: 'You already answered this. Thank you.',
        form_not_invited: 'This questionnaire was not sent to you.',
        form_no_questions: 'There are no questions here yet.',
        form_required: 'This one is required.',
        form_missing_required: 'Some required questions are still empty.',
        form_send_failed: 'That could not be sent. Try again.',
        trash_open: 'Trash ({n})',
        trash_viewing: 'Viewing the trash. These records are not in the list.',
        trash_back: 'Back to the list',
        trash_empty: 'Nothing has been deleted here.',
        trash_restore: 'Restore',
        trash_purge: 'Delete for good',
        trash_purge_title: 'Delete {n} records for good?',
        trash_purge_message: 'This time there is no way back.',
        trash_restored: '{n} restored, {skipped} skipped.',
        trash_purged: '{n} deleted for good, {skipped} skipped.',
        relation_trashed: '(deleted)',
        bulk_delete_dependents:
            '{detail} point at these and will be left without it.',
        bulk_failed: 'That could not be applied.',

        // Offline. Every one of these is a claim about whether something
        // reached the server, so they say which — never just "saved".
        offline_headline: 'No connection',
        offline_last_seen: 'showing the last data downloaded',
        offline_data_from: 'data from {age}',
        offline_just_now: 'just now',
        offline_minutes: '{n} min ago',
        offline_hours: '{n} h ago',
        offline_days: '{n} d ago',
        offline_queued_one: '1 change waiting to be sent',
        offline_queued_many: '{n} changes waiting to be sent',
        offline_sending: 'Sending what was pending…',
        offline_saved_here:
            'Saved on this device. It will be sent when the signal comes back.',
        offline_not_queued: 'This needs a connection. Nothing was saved.',
        offline_rejected_one: '1 change could not be saved',
        offline_rejected_many: '{n} changes could not be saved',
        offline_rejected_detail: 'The server refused it. Nothing was written.',
        offline_rejected_show: 'See what',
        offline_rejected_hide: 'Hide',
        offline_rejected_discard: 'Discard',
        offline_file_held: 'On this device — sent with the form.',
        offline_no_room: 'No room to keep more files on this device.',
        geo_view_on_map: 'See on the map',
        preview_role_as: 'Viewing as «{role}»',
        preview_role_explains: 'This is what that role can reach.',
        preview_role_pick: 'View as…',
        preview_role_none: 'No restrictions (you)',
        preview_role_exit: 'Back to my view',
        preview_more: 'More options',
        exit_to_platform: 'Exit to Sapiensly',
    },
    es: {
        columns: 'Columnas',
        search: 'Buscar…',
        no_matches: 'Ninguna fila coincide con',
        of_loaded: 'entre los primeros {n} de {total}',
        showing_of: 'Mostrando {n} de {total}',
        no_records: 'Todavía no hay nada aquí.',
        no_related: 'Todavía no hay nada ligado a este registro.',
        no_data: 'No hay nada que graficar.',
        menu: 'Menú',
        step_of: 'Paso {n} de {total}',
        load_failed: 'No se pudo cargar esta sección',
        retry: 'Reintentar',
        picker_search: 'Busca un registro…',
        picker_none: 'Ningún registro coincide',
        picker_more: 'Sigue escribiendo para acotar',
        picker_clear: 'Quitar',
        picker_unavailable: 'No disponible aquí',
        filter_all: 'Todos',
        range_today: 'Hoy',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Año',
        range_all: 'Todo',
        range_all_label: 'todo el histórico',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        delete: 'Eliminar',
        thin_series:
            'Todavía no hay suficiente historia para ver una tendencia.',
        activity: 'Actividad',
        leave_a_note: 'Deja una nota…',
        comment_send: 'Comentar',
        no_activity: 'Todavía no ha pasado nada aquí.',
        by_the_app: 'La app',
        event_created: 'lo creó',
        event_updated: 'lo cambió',
        event_deleted: 'lo eliminó',
        event_restored: 'lo restauró',
        event_purged: 'lo eliminó para siempre',
        event_comment: 'escribió',
        bool_yes: 'Sí',
        bool_no: 'No',
        demo_banner: 'Entorno de demo',
        demo_explains: 'Nada de esto son datos reales.',
        demo_leave: 'Volver a producción',
        demo_enter: 'Abrir la demo',
        demo_reset: 'Vaciarla',
        demo_reset_sure: '¿Borrar todos los registros de demo?',
        demo_seed: 'Llenarla con ejemplos',
        bulk_selected: '{n} seleccionados',
        bulk_set: 'Poner {f}…',
        bulk_delete: 'Eliminar',
        bulk_delete_title: '¿Eliminar {n} registros?',
        bulk_delete_message: 'Se van para todos y no se puede deshacer.',
        bulk_done: '{n} cambiados, {skipped} omitidos.',
        bulk_removed: '{n} eliminados, {skipped} omitidos.',
        file_upload: 'Haz clic para subir',
        file_uploading: 'Subiendo {n}%…',
        file_take_photo: 'Tomar una foto',
        file_photo_hint: 'Abre la cámara en el móvil',
        signature_hint: 'Firma con el dedo o con el ratón',
        signature_clear: 'Borrar',
        signature_accept: 'Usar esta firma',
        signature_saved: 'Firmado',
        scan_button: 'Escanear',
        scan_aim: 'Apunta la cámara al código',
        scan_close: 'Cerrar el escáner',
        scan_no_camera: 'No hay cámara disponible. Escribe el código a mano.',
        scan_unsupported:
            'Este navegador no lee códigos. Escribe el código a mano.',
        scan_captured: 'Escaneado',
        geo_lat: 'Latitud',
        geo_lng: 'Longitud',
        geo_locate: 'Usar mi ubicación',
        geo_locating: 'Localizando…',
        geo_denied: 'No se pudo obtener tu ubicación. Escribe las coordenadas.',
        geo_unavailable:
            'Este dispositivo no puede ubicarse. Escribe las coordenadas.',
        geo_pick: 'Elegir en el mapa',
        geo_pick_hint: 'Toca el mapa y arrastra el pin para ajustar',
        geo_pick_accept: 'Usar este punto',
        fill_from_document: 'Rellenar desde una foto o PDF',
        fill_reading: 'Leyendo…',
        fill_failed:
            'No se pudo leer ese documento. Llena el formulario a mano.',
        fill_nothing: 'No se pudo leer nada. Llena el formulario a mano.',
        fill_check: 'Revisa cada dato antes de guardar.',
        fill_from_voice: 'Dictarlo',
        voice_hint: 'Toca para grabar y di lo que va en el formulario',
        voice_listening: 'Escuchando… toca para parar',
        voice_no_mic:
            'No hay micrófono disponible. Llena el formulario a mano.',
        voice_heard: 'Se escuchó: {text}',
        share_copied: 'Enlace copiado — pégalo donde quieras.',
        share_failed: 'No se pudo compartir desde este dispositivo.',
        copy_done: 'Copiado',
        copy_failed: 'No se pudo copiar. Selecciona el texto y cópialo a mano.',
        scan_torch: 'Luz',
        scale_button: 'Pesar',
        scale_reading: 'Leyendo…',
        identity_refused:
            'Esto se tiene que confirmar en tu dispositivo. No se guardó nada.',
        scale_failed: 'La báscula no dio lectura. Escribe el número a mano.',
        geo_auto_note: 'Se tomó la ubicación al abrir este formulario.',
        nfc_button: 'Leer etiqueta',
        nfc_hold: 'Acerca el teléfono a la etiqueta',
        nfc_close: 'Dejar de leer',
        nfc_unsupported:
            'Este dispositivo no puede leer etiquetas NFC. Escribe el código a mano.',
        nfc_denied:
            'El NFC está apagado o se negó el permiso. Escribe el código a mano.',
        nfc_empty: 'Esa etiqueta no trae nada legible.',
        nfc_failed:
            'No se pudo leer la etiqueta. Inténtalo otra vez o escribe el código.',
        contact_button: 'De mis contactos',
        dictate_button: 'Dictar',
        dictate_listening: 'Escuchando…',
        camera_aim: 'Encuadra la foto',
        camera_stamp_hint: 'La foto llevará la fecha, la hora y el lugar',
        camera_close: 'Cerrar la cámara',
        camera_shoot: 'Tomarla',
        camera_retake: 'Tomar otra',
        camera_use: 'Usar esta foto',
        camera_denied: 'No hay cámara disponible. Adjunta un archivo.',
        camera_failed: 'No se pudo guardar la foto. Inténtalo otra vez.',
        screenshot_take: 'Capturar la pantalla',
        screenshot_waiting: 'Elige qué compartir…',
        screenshot_hint: 'Tú eliges qué ventana se captura',
        ask_placeholder: 'Pregunta con tus palabras…',
        ask_showing: 'Mostrando: {q}',
        ask_not_understood:
            'No se pudo convertir esa pregunta en un filtro, así que esta es la lista completa: {q}',
        ask_clear: 'Quitar',
        presence_here: '{who} también tiene esto abierto',
        form_send: 'Enviar',
        form_sending: 'Enviando…',
        form_thanks: 'Gracias — tus respuestas quedaron registradas.',
        form_already_answered: 'Ya contestaste esto. Gracias.',
        form_not_invited: 'Esta encuesta no fue enviada a ti.',
        form_no_questions: 'Todavía no hay preguntas aquí.',
        form_required: 'Esta es obligatoria.',
        form_missing_required: 'Faltan preguntas obligatorias por contestar.',
        form_send_failed: 'No se pudo enviar. Inténtalo otra vez.',
        trash_open: 'Papelera ({n})',
        trash_viewing:
            'Estás en la papelera. Estos registros no salen en la lista.',
        trash_back: 'Volver a la lista',
        trash_empty: 'Aquí no se ha eliminado nada.',
        trash_restore: 'Restaurar',
        trash_purge: 'Eliminar para siempre',
        trash_purge_title: '¿Eliminar {n} registros para siempre?',
        trash_purge_message: 'Esta vez no hay vuelta atrás.',
        trash_restored: '{n} restaurados, {skipped} omitidos.',
        trash_purged: '{n} eliminados para siempre, {skipped} omitidos.',
        relation_trashed: '(eliminado)',
        bulk_delete_dependents:
            '{detail} apuntan a estos y se quedarán sin ese dato.',
        bulk_failed: 'No se pudo aplicar.',

        offline_headline: 'Sin conexión',
        offline_last_seen: 'estás viendo lo último que se descargó',
        offline_data_from: 'datos de {age}',
        offline_just_now: 'hace un momento',
        offline_minutes: 'hace {n} min',
        offline_hours: 'hace {n} h',
        offline_days: 'hace {n} d',
        offline_queued_one: '1 cambio pendiente de enviar',
        offline_queued_many: '{n} cambios pendientes de enviar',
        offline_sending: 'Enviando lo pendiente…',
        offline_saved_here:
            'Guardado en este dispositivo. Se enviará cuando vuelva la señal.',
        offline_not_queued: 'Esto necesita conexión. No se guardó nada.',
        offline_rejected_one: '1 cambio no se pudo guardar',
        offline_rejected_many: '{n} cambios no se pudieron guardar',
        offline_rejected_detail: 'El servidor lo rechazó. No se escribió nada.',
        offline_rejected_show: 'Ver cuáles',
        offline_rejected_hide: 'Ocultar',
        offline_rejected_discard: 'Descartar',
        offline_file_held: 'En este dispositivo — se envía con el formulario.',
        offline_no_room:
            'No hay espacio para guardar más archivos en este dispositivo.',
        geo_view_on_map: 'Ver en el mapa',
        preview_role_as: 'Viendo como «{role}»',
        preview_role_explains: 'Así ve la app este rol.',
        preview_role_pick: 'Ver la app como…',
        preview_role_none: 'Sin restricciones (tú)',
        preview_role_exit: 'Volver a mi vista',
        preview_more: 'Más opciones',
        exit_to_platform: 'Salir a Sapiensly',
    },
    pt: {
        columns: 'Colunas',
        search: 'Pesquisar…',
        no_matches: 'Nenhuma linha corresponde a',
        of_loaded: 'entre os primeiros {n} de {total}',
        showing_of: 'Mostrando {n} de {total}',
        no_records: 'Ainda não há nada aqui.',
        no_related: 'Ainda não há nada ligado a este registro.',
        no_data: 'Não há nada para plotar.',
        menu: 'Menu',
        step_of: 'Passo {n} de {total}',
        load_failed: 'Não foi possível carregar esta seção',
        retry: 'Tentar de novo',
        picker_search: 'Busque um registro…',
        picker_none: 'Nenhum registro corresponde',
        picker_more: 'Continue digitando para restringir',
        picker_clear: 'Remover',
        picker_unavailable: 'Não disponível aqui',
        filter_all: 'Todos',
        range_today: 'Hoje',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Ano',
        range_all: 'Tudo',
        range_all_label: 'todo o histórico',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        delete: 'Excluir',
        thin_series:
            'Ainda não há histórico suficiente para ver uma tendência.',
        activity: 'Atividade',
        leave_a_note: 'Deixe uma nota…',
        comment_send: 'Comentar',
        no_activity: 'Ainda não aconteceu nada aqui.',
        by_the_app: 'O app',
        event_created: 'criou',
        event_updated: 'alterou',
        event_deleted: 'excluiu',
        event_restored: 'restaurou',
        event_purged: 'excluiu de vez',
        event_comment: 'escreveu',
        bool_yes: 'Sim',
        bool_no: 'Não',
        demo_banner: 'Ambiente de demonstração',
        demo_explains: 'Nada aqui são dados reais.',
        demo_leave: 'Voltar à produção',
        demo_enter: 'Abrir a demonstração',
        demo_reset: 'Esvaziar',
        demo_reset_sure: 'Excluir todos os registros de demonstração?',
        demo_seed: 'Preencher com exemplos',
        bulk_selected: '{n} selecionados',
        bulk_set: 'Definir {f}…',
        bulk_delete: 'Excluir',
        bulk_delete_title: 'Excluir {n} registros?',
        bulk_delete_message: 'Somem para todos e não dá para desfazer.',
        bulk_done: '{n} alterados, {skipped} ignorados.',
        bulk_removed: '{n} excluídos, {skipped} ignorados.',
        file_upload: 'Clique para enviar',
        file_uploading: 'Enviando {n}%…',
        file_take_photo: 'Tirar uma foto',
        file_photo_hint: 'Abre a câmera no celular',
        signature_hint: 'Assine com o dedo ou com o mouse',
        signature_clear: 'Apagar',
        signature_accept: 'Usar esta assinatura',
        signature_saved: 'Assinado',
        scan_button: 'Escanear',
        scan_aim: 'Aponte a câmera para o código',
        scan_close: 'Fechar o leitor',
        scan_no_camera: 'Sem câmera disponível. Digite o código.',
        scan_unsupported: 'Este navegador não lê códigos. Digite o código.',
        scan_captured: 'Lido',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Usar minha localização',
        geo_locating: 'Localizando…',
        geo_denied:
            'Não foi possível obter sua localização. Digite as coordenadas.',
        geo_unavailable:
            'Este aparelho não consegue se localizar. Digite as coordenadas.',
        geo_pick: 'Escolher no mapa',
        geo_pick_hint: 'Toque no mapa e arraste o pino para ajustar',
        geo_pick_accept: 'Usar este ponto',
        fill_from_document: 'Preencher de uma foto ou PDF',
        fill_reading: 'Lendo…',
        fill_failed: 'Não foi possível ler o documento. Preencha à mão.',
        fill_nothing: 'Nada pôde ser lido. Preencha à mão.',
        fill_check: 'Confira cada dado antes de salvar.',
        fill_from_voice: 'Ditar',
        voice_hint: 'Toque para gravar e diga o que vai no formulário',
        voice_listening: 'Ouvindo… toque para parar',
        voice_no_mic: 'Sem microfone disponível. Preencha à mão.',
        voice_heard: 'Ouvi: {text}',
        share_copied: 'Link copiado — cole onde quiser.',
        share_failed: 'Não foi possível compartilhar deste aparelho.',
        copy_done: 'Copiado',
        copy_failed:
            'Não foi possível copiar. Selecione o texto e copie à mão.',
        scan_torch: 'Luz',
        scale_button: 'Pesar',
        scale_reading: 'Lendo…',
        identity_refused:
            'Isto precisa ser confirmado no seu aparelho. Nada foi salvo.',
        scale_failed: 'A balança não deu leitura. Digite o número à mão.',
        geo_auto_note: 'A localização foi obtida ao abrir este formulário.',
        nfc_button: 'Ler etiqueta',
        nfc_hold: 'Encoste o telefone na etiqueta',
        nfc_close: 'Parar de ler',
        nfc_unsupported:
            'Este aparelho não lê etiquetas NFC. Digite o código à mão.',
        nfc_denied: 'O NFC está desligado ou foi recusado. Digite o código.',
        nfc_empty: 'Essa etiqueta não traz nada legível.',
        nfc_failed:
            'Não foi possível ler a etiqueta. Tente de novo ou digite o código.',
        contact_button: 'Dos meus contatos',
        dictate_button: 'Ditar',
        dictate_listening: 'Ouvindo…',
        camera_aim: 'Enquadre a foto',
        camera_stamp_hint: 'A foto vai levar a data, a hora e o lugar',
        camera_close: 'Fechar a câmera',
        camera_shoot: 'Tirar',
        camera_retake: 'Tirar outra',
        camera_use: 'Usar esta foto',
        camera_denied: 'Sem câmera disponível. Anexe um arquivo.',
        camera_failed: 'Não foi possível salvar a foto. Tente de novo.',
        screenshot_take: 'Capturar a tela',
        screenshot_waiting: 'Escolha o que compartilhar…',
        screenshot_hint: 'Você escolhe qual janela é capturada',
        ask_placeholder: 'Pergunte com suas palavras…',
        ask_showing: 'Mostrando: {q}',
        ask_not_understood:
            'Não foi possível transformar essa pergunta em filtro, então esta é a lista inteira: {q}',
        ask_clear: 'Remover',
        presence_here: '{who} também está com isto aberto',
        form_send: 'Enviar',
        form_sending: 'Enviando…',
        form_thanks: 'Obrigado — suas respostas foram registradas.',
        form_already_answered: 'Você já respondeu isto. Obrigado.',
        form_not_invited: 'Este questionário não foi enviado a você.',
        form_no_questions: 'Ainda não há perguntas aqui.',
        form_required: 'Esta é obrigatória.',
        form_missing_required: 'Faltam perguntas obrigatórias.',
        form_send_failed: 'Não foi possível enviar. Tente de novo.',
        trash_open: 'Lixeira ({n})',
        trash_viewing:
            'Você está na lixeira. Estes registros não aparecem na lista.',
        trash_back: 'Voltar para a lista',
        trash_empty: 'Aqui nada foi excluído.',
        trash_restore: 'Restaurar',
        trash_purge: 'Excluir de vez',
        trash_purge_title: 'Excluir {n} registros de vez?',
        trash_purge_message: 'Desta vez não tem volta.',
        trash_restored: '{n} restaurados, {skipped} ignorados.',
        trash_purged: '{n} excluídos de vez, {skipped} ignorados.',
        relation_trashed: '(excluído)',
        bulk_delete_dependents:
            '{detail} apontam para estes e ficarão sem esse dado.',
        bulk_failed: 'Não foi possível aplicar.',

        offline_headline: 'Sem ligação',
        offline_last_seen: 'está a ver os últimos dados descarregados',
        offline_data_from: 'dados de {age}',
        offline_just_now: 'agora mesmo',
        offline_minutes: 'há {n} min',
        offline_hours: 'há {n} h',
        offline_days: 'há {n} d',
        offline_queued_one: '1 alteração à espera de ser enviada',
        offline_queued_many: '{n} alterações à espera de serem enviadas',
        offline_sending: 'A enviar o que estava pendente…',
        offline_saved_here:
            'Guardado neste dispositivo. Será enviado quando houver sinal.',
        offline_not_queued: 'Isto precisa de ligação. Nada foi guardado.',
        offline_rejected_one: '1 alteração não pôde ser guardada',
        offline_rejected_many: '{n} alterações não puderam ser guardadas',
        offline_rejected_detail: 'O servidor recusou-a. Nada foi escrito.',
        offline_rejected_show: 'Ver quais',
        offline_rejected_hide: 'Ocultar',
        offline_rejected_discard: 'Descartar',
        offline_file_held: 'Neste dispositivo — enviado com o formulário.',
        offline_no_room:
            'Não há espaço para guardar mais ficheiros neste dispositivo.',
        geo_view_on_map: 'Ver no mapa',
        preview_role_as: 'A ver como «{role}»',
        preview_role_explains: 'É assim que este perfil vê a aplicação.',
        preview_role_pick: 'Ver a aplicação como…',
        preview_role_none: 'Sem restrições (você)',
        preview_role_exit: 'Voltar à minha vista',
        preview_more: 'Mais opções',
        exit_to_platform: 'Sair para o Sapiensly',
    },
    fr: {
        columns: 'Colonnes',
        search: 'Rechercher…',
        no_matches: 'Aucune ligne ne correspond à',
        of_loaded: 'parmi les {n} premiers sur {total}',
        showing_of: 'Affichage de {n} sur {total}',
        no_records: 'Il n’y a encore rien ici.',
        no_related: 'Rien n’est encore lié à cet enregistrement.',
        no_data: 'Rien à tracer.',
        menu: 'Menu',
        step_of: 'Étape {n} sur {total}',
        load_failed: 'Cette section n’a pas pu être chargée',
        retry: 'Réessayer',
        picker_search: 'Cherchez un enregistrement…',
        picker_none: 'Aucun enregistrement ne correspond',
        picker_more: 'Continuez à taper pour affiner',
        picker_clear: 'Retirer',
        picker_unavailable: 'Indisponible ici',
        filter_all: 'Tous',
        range_today: 'Aujourd’hui',
        range_7d: '7 j',
        range_30d: '30 j',
        range_90d: '90 j',
        range_1y: 'Année',
        range_all: 'Tout',
        range_all_label: 'tout l’historique',
        cancel: 'Annuler',
        confirm: 'Confirmer',
        delete: 'Supprimer',
        thin_series: 'Pas encore assez d’historique pour voir une tendance.',
        activity: 'Activité',
        leave_a_note: 'Laissez une note…',
        comment_send: 'Commenter',
        no_activity: 'Il ne s’est encore rien passé ici.',
        by_the_app: 'L’application',
        event_created: 'l’a créé',
        event_updated: 'l’a modifié',
        event_deleted: 'l’a supprimé',
        event_restored: 'l’a restauré',
        event_purged: 'l’a supprimé définitivement',
        event_comment: 'a écrit',
        bool_yes: 'Oui',
        bool_no: 'Non',
        demo_banner: 'Environnement de démo',
        demo_explains: 'Rien ici n’est une donnée réelle.',
        demo_leave: 'Retour à la production',
        demo_enter: 'Ouvrir la démo',
        demo_reset: 'La vider',
        demo_reset_sure: 'Supprimer tous les enregistrements de démo ?',
        demo_seed: 'La remplir d’exemples',
        bulk_selected: '{n} sélectionnés',
        bulk_set: 'Définir {f}…',
        bulk_delete: 'Supprimer',
        bulk_delete_title: 'Supprimer {n} enregistrements ?',
        bulk_delete_message:
            'Ils disparaissent pour tout le monde, sans retour.',
        bulk_done: '{n} modifiés, {skipped} ignorés.',
        bulk_removed: '{n} supprimés, {skipped} ignorés.',
        file_upload: 'Cliquez pour envoyer',
        file_uploading: 'Envoi {n}%…',
        file_take_photo: 'Prendre une photo',
        file_photo_hint: 'Ouvre l’appareil photo sur mobile',
        signature_hint: 'Signez avec le doigt ou la souris',
        signature_clear: 'Effacer',
        signature_accept: 'Utiliser cette signature',
        signature_saved: 'Signé',
        scan_button: 'Scanner',
        scan_aim: 'Visez le code avec la caméra',
        scan_close: 'Fermer le scanner',
        scan_no_camera: 'Aucune caméra disponible. Saisissez le code.',
        scan_unsupported:
            'Ce navigateur ne lit pas les codes. Saisissez le code.',
        scan_captured: 'Scanné',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Utiliser ma position',
        geo_locating: 'Localisation…',
        geo_denied: 'Position indisponible. Saisissez les coordonnées.',
        geo_unavailable:
            'Cet appareil ne peut pas se localiser. Saisissez les coordonnées.',
        geo_pick: 'Choisir sur la carte',
        geo_pick_hint: 'Touchez la carte, puis déplacez le repère',
        geo_pick_accept: 'Utiliser ce point',
        fill_from_document: 'Remplir depuis une photo ou un PDF',
        fill_reading: 'Lecture…',
        fill_failed: 'Ce document n’a pas pu être lu. Remplissez à la main.',
        fill_nothing: 'Rien n’a pu être lu. Remplissez à la main.',
        fill_check: 'Vérifiez chaque valeur avant d’enregistrer.',
        fill_from_voice: 'Dicter',
        voice_hint:
            'Touchez pour enregistrer, puis dites ce qui va dans le formulaire',
        voice_listening: 'À l’écoute… touchez pour arrêter',
        voice_no_mic: 'Aucun micro disponible. Remplissez à la main.',
        voice_heard: 'Entendu : {text}',
        share_copied: 'Lien copié — collez-le où vous voulez.',
        share_failed: 'Impossible de partager depuis cet appareil.',
        copy_done: 'Copié',
        copy_failed:
            'Impossible de copier. Sélectionnez le texte et copiez-le à la main.',
        scan_torch: 'Lumière',
        scale_button: 'Peser',
        identity_refused:
            'Ceci doit être confirmé sur votre appareil. Rien n’a été enregistré.',
        scale_reading: 'Lecture…',
        scale_failed: 'Aucune lecture de la balance. Saisissez le nombre.',
        geo_auto_note: 'Position relevée à l’ouverture de ce formulaire.',
        nfc_button: 'Lire une étiquette',
        nfc_hold: 'Approchez le téléphone de l’étiquette',
        nfc_close: 'Arrêter la lecture',
        nfc_unsupported:
            'Cet appareil ne lit pas les étiquettes NFC. Saisissez le code.',
        nfc_denied: 'Le NFC est désactivé ou refusé. Saisissez le code.',
        nfc_empty: 'Cette étiquette ne contient rien de lisible.',
        nfc_failed:
            'Cette étiquette n’a pas pu être lue. Réessayez ou saisissez le code.',
        contact_button: 'Depuis mes contacts',
        dictate_button: 'Dicter',
        dictate_listening: 'À l’écoute…',
        camera_aim: 'Cadrez la photo',
        camera_stamp_hint: 'La photo portera la date, l’heure et le lieu',
        camera_close: 'Fermer la caméra',
        camera_shoot: 'Prendre',
        camera_retake: 'En reprendre une',
        camera_use: 'Utiliser cette photo',
        camera_denied: 'Aucune caméra disponible. Joignez un fichier.',
        camera_failed: 'Cette photo n’a pas pu être enregistrée. Réessayez.',
        screenshot_take: 'Capturer l’écran',
        screenshot_waiting: 'Choisissez quoi partager…',
        screenshot_hint: 'Vous choisissez la fenêtre capturée',
        ask_placeholder: 'Demandez avec vos mots…',
        ask_showing: 'Affichage : {q}',
        ask_not_understood:
            'Cette question n’a pas pu devenir un filtre : voici donc la liste complète. {q}',
        ask_clear: 'Retirer',
        presence_here: '{who} a aussi ceci ouvert',
        form_send: 'Envoyer',
        form_sending: 'Envoi…',
        form_thanks: 'Merci — vos réponses ont été enregistrées.',
        form_already_answered: 'Vous avez déjà répondu. Merci.',
        form_not_invited: 'Ce questionnaire ne vous a pas été envoyé.',
        form_no_questions: 'Il n’y a pas encore de questions ici.',
        form_required: 'Celle-ci est obligatoire.',
        form_missing_required: 'Des questions obligatoires sont vides.',
        form_send_failed: 'L’envoi a échoué. Réessayez.',
        trash_open: 'Corbeille ({n})',
        trash_viewing:
            'Vous êtes dans la corbeille. Ces enregistrements ne figurent pas dans la liste.',
        trash_back: 'Retour à la liste',
        trash_empty: 'Rien n’a été supprimé ici.',
        trash_restore: 'Restaurer',
        trash_purge: 'Supprimer définitivement',
        trash_purge_title: 'Supprimer définitivement {n} enregistrements ?',
        trash_purge_message: 'Cette fois, il n’y a pas de retour en arrière.',
        trash_restored: '{n} restaurés, {skipped} ignorés.',
        trash_purged: '{n} supprimés définitivement, {skipped} ignorés.',
        relation_trashed: '(supprimé)',
        bulk_delete_dependents:
            '{detail} pointent vers ceux-ci et se retrouveront sans cette donnée.',
        bulk_failed: 'Impossible à appliquer.',

        offline_headline: 'Hors connexion',
        offline_last_seen: 'vous voyez les dernières données téléchargées',
        offline_data_from: 'données de {age}',
        offline_just_now: 'à l’instant',
        offline_minutes: 'il y a {n} min',
        offline_hours: 'il y a {n} h',
        offline_days: 'il y a {n} j',
        offline_queued_one: '1 modification en attente d’envoi',
        offline_queued_many: '{n} modifications en attente d’envoi',
        offline_sending: 'Envoi de ce qui était en attente…',
        offline_saved_here:
            'Enregistré sur cet appareil. Sera envoyé au retour du réseau.',
        offline_not_queued:
            'Ceci exige une connexion. Rien n’a été enregistré.',
        offline_rejected_one: '1 modification n’a pas pu être enregistrée',
        offline_rejected_many:
            '{n} modifications n’ont pas pu être enregistrées',
        offline_rejected_detail: 'Le serveur l’a refusée. Rien n’a été écrit.',
        offline_rejected_show: 'Voir lesquelles',
        offline_rejected_hide: 'Masquer',
        offline_rejected_discard: 'Écarter',
        offline_file_held: 'Sur cet appareil — envoyé avec le formulaire.',
        offline_no_room:
            'Plus de place pour garder des fichiers sur cet appareil.',
        geo_view_on_map: 'Voir sur la carte',
        preview_role_as: 'Vue en tant que «{role}»',
        preview_role_explains: 'Voici ce que ce rôle peut atteindre.',
        preview_role_pick: 'Voir l’application en tant que…',
        preview_role_none: 'Sans restrictions (vous)',
        preview_role_exit: 'Revenir à ma vue',
        preview_more: 'Plus d’options',
        exit_to_platform: 'Quitter vers Sapiensly',
    },
};

/**
 * The keys a language is missing against the English table.
 *
 * Asked this way rather than by comparing VALUES: an abbreviation is often the
 * same string in several languages ("30 d"), and a value-difference check
 * reports those as untranslated while quietly accepting a key that fell back.
 * Mirrors DocWords::missingKeys on the PHP side.
 */
export function missingWordKeys(lang: string): string[] {
    const table = WORDS[lang] ?? {};

    return Object.keys(WORDS.en).filter((key) => !(key in table));
}

/** Every language the runtime claims to speak. */
export function wordLanguages(): string[] {
    return Object.keys(WORDS);
}

/**
 * One phrase, in the app's language, with its placeholders filled.
 *
 * @param locale the APP's locale, not the platform session's
 */
export function runtimeWord(
    locale: string | undefined,
    key: string,
    replace: Record<string, string | number> = {},
): string {
    const lang = (locale ?? 'en').slice(0, 2).toLowerCase();
    let out = WORDS[lang]?.[key] ?? WORDS.en[key] ?? key;

    for (const [token, value] of Object.entries(replace)) {
        out = out.replace(`{${token}}`, String(value));
    }

    return out;
}
