/**
 * The runtime's own words.
 *
 * Not the app's content — that comes from the manifest, in whatever language it
 * was written. These are the handful of things the runtime says on its own
 * behalf: an empty table, a search box, the count of what did not fit.
 *
 * They lived as hardcoded English in five components and as four separate
 * word-maps in four others, so a Spanish app told its user "No related
 * records." and an English one had a menu labelled "Menú" depending on which
 * component was speaking. One place, keyed by the APP's locale rather than the
 * platform session's: an app is read by its users, who did not choose the
 * language of the person who built it.
 *
 * English is the fallback for a language not listed, which is a choice about
 * being readable rather than about being right — a missing translation should
 * degrade to a word, not to a key.
 */
type Dict = Record<string, string>;

const WORDS: Record<string, Dict> = {
    en: {
        columns: 'Columns',
        search: 'Search…',
        no_matches: 'No row matches',
        of_loaded: 'among the first {n} of {total}',
        showing_of: 'Showing {n} of {total}',
        no_records: 'Nothing here yet.',
        no_related: 'Nothing linked to this record yet.',
        no_data: 'Nothing to plot.',
        menu: 'Menu',
        step_of: 'Step {n} of {total}',
        load_failed: 'This section could not be loaded',
        retry: 'Try again',
        picker_search: 'Search a record…',
        picker_none: 'No record matches',
        picker_more: 'Keep typing to narrow it down',
        picker_clear: 'Clear',
        picker_unavailable: 'Not available here',
        filter_all: 'All',
        range_today: 'Today',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Year',
        range_all: 'All time',
        range_all_label: 'the whole history',
        cancel: 'Cancel',
        confirm: 'Confirm',
        delete: 'Delete',
        thin_series: 'Not enough history yet to show a trend.',
        activity: 'Activity',
        leave_a_note: 'Leave a note…',
        comment_send: 'Comment',
        no_activity: 'Nothing has happened here yet.',
        by_the_app: 'The app',
        event_created: 'created it',
        event_updated: 'changed it',
        event_deleted: 'deleted it',
        event_restored: 'restored it',
        event_purged: 'deleted it for good',
        event_comment: 'wrote',
        bool_yes: 'Yes',
        bool_no: 'No',
        demo_banner: 'Demo environment',
        demo_explains: 'Nothing here is real data.',
        demo_leave: 'Back to production',
        demo_enter: 'Open the demo',
        demo_reset: 'Empty it',
        demo_reset_sure: 'Delete every demo record?',
        demo_seed: 'Fill it with samples',
        bulk_selected: '{n} selected',
        bulk_set: 'Set {f}…',
        bulk_delete: 'Delete',
        bulk_delete_title: 'Delete {n} records?',
        bulk_delete_message: 'They go for everyone, and this cannot be undone.',
        bulk_done: '{n} changed, {skipped} skipped.',
        bulk_removed: '{n} deleted, {skipped} skipped.',
        file_upload: 'Click to upload',
        file_uploading: 'Uploading {n}%…',
        file_take_photo: 'Take a photo',
        file_photo_hint: 'Opens the camera on a phone',
        signature_hint: 'Sign with your finger or the mouse',
        signature_clear: 'Clear',
        signature_accept: 'Use this signature',
        signature_saved: 'Signed',
        scan_button: 'Scan',
        scan_aim: 'Point the camera at the barcode',
        scan_close: 'Close the scanner',
        scan_no_camera: 'No camera available. Type the code instead.',
        scan_unsupported:
            'This browser cannot read barcodes. Type the code instead.',
        scan_captured: 'Scanned',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Use my location',
        geo_locating: 'Locating…',
        geo_denied:
            'Could not get your location. Type the coordinates instead.',
        geo_unavailable:
            'This device cannot locate itself. Type the coordinates instead.',
        geo_pick: 'Pick on a map',
        geo_pick_hint: 'Tap the map, then drag the pin to adjust',
        geo_pick_accept: 'Use this point',
        fill_from_document: 'Fill from a photo or PDF',
        fill_reading: 'Reading…',
        fill_failed: 'That document could not be read. Fill the form by hand.',
        fill_nothing: 'Nothing could be read from it. Fill the form by hand.',
        fill_check: 'Check every value before saving.',
        trash_open: 'Trash ({n})',
        trash_viewing: 'Viewing the trash. These records are not in the list.',
        trash_back: 'Back to the list',
        trash_empty: 'Nothing has been deleted here.',
        trash_restore: 'Restore',
        trash_purge: 'Delete for good',
        trash_purge_title: 'Delete {n} records for good?',
        trash_purge_message: 'This time there is no way back.',
        trash_restored: '{n} restored, {skipped} skipped.',
        trash_purged: '{n} deleted for good, {skipped} skipped.',
        relation_trashed: '(deleted)',
        bulk_delete_dependents:
            '{detail} point at these and will be left without it.',
        bulk_failed: 'That could not be applied.',
    },
    es: {
        columns: 'Columnas',
        search: 'Buscar…',
        no_matches: 'Ninguna fila coincide con',
        of_loaded: 'entre los primeros {n} de {total}',
        showing_of: 'Mostrando {n} de {total}',
        no_records: 'Todavía no hay nada aquí.',
        no_related: 'Todavía no hay nada ligado a este registro.',
        no_data: 'No hay nada que graficar.',
        menu: 'Menú',
        step_of: 'Paso {n} de {total}',
        load_failed: 'No se pudo cargar esta sección',
        retry: 'Reintentar',
        picker_search: 'Busca un registro…',
        picker_none: 'Ningún registro coincide',
        picker_more: 'Sigue escribiendo para acotar',
        picker_clear: 'Quitar',
        picker_unavailable: 'No disponible aquí',
        filter_all: 'Todos',
        range_today: 'Hoy',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Año',
        range_all: 'Todo',
        range_all_label: 'todo el histórico',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        delete: 'Eliminar',
        thin_series:
            'Todavía no hay suficiente historia para ver una tendencia.',
        activity: 'Actividad',
        leave_a_note: 'Deja una nota…',
        comment_send: 'Comentar',
        no_activity: 'Todavía no ha pasado nada aquí.',
        by_the_app: 'La app',
        event_created: 'lo creó',
        event_updated: 'lo cambió',
        event_deleted: 'lo eliminó',
        event_restored: 'lo restauró',
        event_purged: 'lo eliminó para siempre',
        event_comment: 'escribió',
        bool_yes: 'Sí',
        bool_no: 'No',
        demo_banner: 'Entorno de demo',
        demo_explains: 'Nada de esto son datos reales.',
        demo_leave: 'Volver a producción',
        demo_enter: 'Abrir la demo',
        demo_reset: 'Vaciarla',
        demo_reset_sure: '¿Borrar todos los registros de demo?',
        demo_seed: 'Llenarla con ejemplos',
        bulk_selected: '{n} seleccionados',
        bulk_set: 'Poner {f}…',
        bulk_delete: 'Eliminar',
        bulk_delete_title: '¿Eliminar {n} registros?',
        bulk_delete_message: 'Se van para todos y no se puede deshacer.',
        bulk_done: '{n} cambiados, {skipped} omitidos.',
        bulk_removed: '{n} eliminados, {skipped} omitidos.',
        file_upload: 'Haz clic para subir',
        file_uploading: 'Subiendo {n}%…',
        file_take_photo: 'Tomar una foto',
        file_photo_hint: 'Abre la cámara en el móvil',
        signature_hint: 'Firma con el dedo o con el ratón',
        signature_clear: 'Borrar',
        signature_accept: 'Usar esta firma',
        signature_saved: 'Firmado',
        scan_button: 'Escanear',
        scan_aim: 'Apunta la cámara al código',
        scan_close: 'Cerrar el escáner',
        scan_no_camera: 'No hay cámara disponible. Escribe el código a mano.',
        scan_unsupported:
            'Este navegador no lee códigos. Escribe el código a mano.',
        scan_captured: 'Escaneado',
        geo_lat: 'Latitud',
        geo_lng: 'Longitud',
        geo_locate: 'Usar mi ubicación',
        geo_locating: 'Localizando…',
        geo_denied: 'No se pudo obtener tu ubicación. Escribe las coordenadas.',
        geo_unavailable:
            'Este dispositivo no puede ubicarse. Escribe las coordenadas.',
        geo_pick: 'Elegir en el mapa',
        geo_pick_hint: 'Toca el mapa y arrastra el pin para ajustar',
        geo_pick_accept: 'Usar este punto',
        fill_from_document: 'Rellenar desde una foto o PDF',
        fill_reading: 'Leyendo…',
        fill_failed:
            'No se pudo leer ese documento. Llena el formulario a mano.',
        fill_nothing: 'No se pudo leer nada. Llena el formulario a mano.',
        fill_check: 'Revisa cada dato antes de guardar.',
        trash_open: 'Papelera ({n})',
        trash_viewing:
            'Estás en la papelera. Estos registros no salen en la lista.',
        trash_back: 'Volver a la lista',
        trash_empty: 'Aquí no se ha eliminado nada.',
        trash_restore: 'Restaurar',
        trash_purge: 'Eliminar para siempre',
        trash_purge_title: '¿Eliminar {n} registros para siempre?',
        trash_purge_message: 'Esta vez no hay vuelta atrás.',
        trash_restored: '{n} restaurados, {skipped} omitidos.',
        trash_purged: '{n} eliminados para siempre, {skipped} omitidos.',
        relation_trashed: '(eliminado)',
        bulk_delete_dependents:
            '{detail} apuntan a estos y se quedarán sin ese dato.',
        bulk_failed: 'No se pudo aplicar.',
    },
    pt: {
        columns: 'Colunas',
        search: 'Pesquisar…',
        no_matches: 'Nenhuma linha corresponde a',
        of_loaded: 'entre os primeiros {n} de {total}',
        showing_of: 'Mostrando {n} de {total}',
        no_records: 'Ainda não há nada aqui.',
        no_related: 'Ainda não há nada ligado a este registro.',
        no_data: 'Não há nada para plotar.',
        menu: 'Menu',
        step_of: 'Passo {n} de {total}',
        load_failed: 'Não foi possível carregar esta seção',
        retry: 'Tentar de novo',
        picker_search: 'Busque um registro…',
        picker_none: 'Nenhum registro corresponde',
        picker_more: 'Continue digitando para restringir',
        picker_clear: 'Remover',
        picker_unavailable: 'Não disponível aqui',
        filter_all: 'Todos',
        range_today: 'Hoje',
        range_7d: '7 d',
        range_30d: '30 d',
        range_90d: '90 d',
        range_1y: 'Ano',
        range_all: 'Tudo',
        range_all_label: 'todo o histórico',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        delete: 'Excluir',
        thin_series:
            'Ainda não há histórico suficiente para ver uma tendência.',
        activity: 'Atividade',
        leave_a_note: 'Deixe uma nota…',
        comment_send: 'Comentar',
        no_activity: 'Ainda não aconteceu nada aqui.',
        by_the_app: 'O app',
        event_created: 'criou',
        event_updated: 'alterou',
        event_deleted: 'excluiu',
        event_restored: 'restaurou',
        event_purged: 'excluiu de vez',
        event_comment: 'escreveu',
        bool_yes: 'Sim',
        bool_no: 'Não',
        demo_banner: 'Ambiente de demonstração',
        demo_explains: 'Nada aqui são dados reais.',
        demo_leave: 'Voltar à produção',
        demo_enter: 'Abrir a demonstração',
        demo_reset: 'Esvaziar',
        demo_reset_sure: 'Excluir todos os registros de demonstração?',
        demo_seed: 'Preencher com exemplos',
        bulk_selected: '{n} selecionados',
        bulk_set: 'Definir {f}…',
        bulk_delete: 'Excluir',
        bulk_delete_title: 'Excluir {n} registros?',
        bulk_delete_message: 'Somem para todos e não dá para desfazer.',
        bulk_done: '{n} alterados, {skipped} ignorados.',
        bulk_removed: '{n} excluídos, {skipped} ignorados.',
        file_upload: 'Clique para enviar',
        file_uploading: 'Enviando {n}%…',
        file_take_photo: 'Tirar uma foto',
        file_photo_hint: 'Abre a câmera no celular',
        signature_hint: 'Assine com o dedo ou com o mouse',
        signature_clear: 'Apagar',
        signature_accept: 'Usar esta assinatura',
        signature_saved: 'Assinado',
        scan_button: 'Escanear',
        scan_aim: 'Aponte a câmera para o código',
        scan_close: 'Fechar o leitor',
        scan_no_camera: 'Sem câmera disponível. Digite o código.',
        scan_unsupported: 'Este navegador não lê códigos. Digite o código.',
        scan_captured: 'Lido',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Usar minha localização',
        geo_locating: 'Localizando…',
        geo_denied:
            'Não foi possível obter sua localização. Digite as coordenadas.',
        geo_unavailable:
            'Este aparelho não consegue se localizar. Digite as coordenadas.',
        geo_pick: 'Escolher no mapa',
        geo_pick_hint: 'Toque no mapa e arraste o pino para ajustar',
        geo_pick_accept: 'Usar este ponto',
        fill_from_document: 'Preencher de uma foto ou PDF',
        fill_reading: 'Lendo…',
        fill_failed: 'Não foi possível ler o documento. Preencha à mão.',
        fill_nothing: 'Nada pôde ser lido. Preencha à mão.',
        fill_check: 'Confira cada dado antes de salvar.',
        trash_open: 'Lixeira ({n})',
        trash_viewing:
            'Você está na lixeira. Estes registros não aparecem na lista.',
        trash_back: 'Voltar para a lista',
        trash_empty: 'Aqui nada foi excluído.',
        trash_restore: 'Restaurar',
        trash_purge: 'Excluir de vez',
        trash_purge_title: 'Excluir {n} registros de vez?',
        trash_purge_message: 'Desta vez não tem volta.',
        trash_restored: '{n} restaurados, {skipped} ignorados.',
        trash_purged: '{n} excluídos de vez, {skipped} ignorados.',
        relation_trashed: '(excluído)',
        bulk_delete_dependents:
            '{detail} apontam para estes e ficarão sem esse dado.',
        bulk_failed: 'Não foi possível aplicar.',
    },
    fr: {
        columns: 'Colonnes',
        search: 'Rechercher…',
        no_matches: 'Aucune ligne ne correspond à',
        of_loaded: 'parmi les {n} premiers sur {total}',
        showing_of: 'Affichage de {n} sur {total}',
        no_records: 'Il n’y a encore rien ici.',
        no_related: 'Rien n’est encore lié à cet enregistrement.',
        no_data: 'Rien à tracer.',
        menu: 'Menu',
        step_of: 'Étape {n} sur {total}',
        load_failed: 'Cette section n’a pas pu être chargée',
        retry: 'Réessayer',
        picker_search: 'Cherchez un enregistrement…',
        picker_none: 'Aucun enregistrement ne correspond',
        picker_more: 'Continuez à taper pour affiner',
        picker_clear: 'Retirer',
        picker_unavailable: 'Indisponible ici',
        filter_all: 'Tous',
        range_today: 'Aujourd’hui',
        range_7d: '7 j',
        range_30d: '30 j',
        range_90d: '90 j',
        range_1y: 'Année',
        range_all: 'Tout',
        range_all_label: 'tout l’historique',
        cancel: 'Annuler',
        confirm: 'Confirmer',
        delete: 'Supprimer',
        thin_series: 'Pas encore assez d’historique pour voir une tendance.',
        activity: 'Activité',
        leave_a_note: 'Laissez une note…',
        comment_send: 'Commenter',
        no_activity: 'Il ne s’est encore rien passé ici.',
        by_the_app: 'L’application',
        event_created: 'l’a créé',
        event_updated: 'l’a modifié',
        event_deleted: 'l’a supprimé',
        event_restored: 'l’a restauré',
        event_purged: 'l’a supprimé définitivement',
        event_comment: 'a écrit',
        bool_yes: 'Oui',
        bool_no: 'Non',
        demo_banner: 'Environnement de démo',
        demo_explains: 'Rien ici n’est une donnée réelle.',
        demo_leave: 'Retour à la production',
        demo_enter: 'Ouvrir la démo',
        demo_reset: 'La vider',
        demo_reset_sure: 'Supprimer tous les enregistrements de démo ?',
        demo_seed: 'La remplir d’exemples',
        bulk_selected: '{n} sélectionnés',
        bulk_set: 'Définir {f}…',
        bulk_delete: 'Supprimer',
        bulk_delete_title: 'Supprimer {n} enregistrements ?',
        bulk_delete_message:
            'Ils disparaissent pour tout le monde, sans retour.',
        bulk_done: '{n} modifiés, {skipped} ignorés.',
        bulk_removed: '{n} supprimés, {skipped} ignorés.',
        file_upload: 'Cliquez pour envoyer',
        file_uploading: 'Envoi {n}%…',
        file_take_photo: 'Prendre une photo',
        file_photo_hint: 'Ouvre l’appareil photo sur mobile',
        signature_hint: 'Signez avec le doigt ou la souris',
        signature_clear: 'Effacer',
        signature_accept: 'Utiliser cette signature',
        signature_saved: 'Signé',
        scan_button: 'Scanner',
        scan_aim: 'Visez le code avec la caméra',
        scan_close: 'Fermer le scanner',
        scan_no_camera: 'Aucune caméra disponible. Saisissez le code.',
        scan_unsupported:
            'Ce navigateur ne lit pas les codes. Saisissez le code.',
        scan_captured: 'Scanné',
        geo_lat: 'Latitude',
        geo_lng: 'Longitude',
        geo_locate: 'Utiliser ma position',
        geo_locating: 'Localisation…',
        geo_denied: 'Position indisponible. Saisissez les coordonnées.',
        geo_unavailable:
            'Cet appareil ne peut pas se localiser. Saisissez les coordonnées.',
        geo_pick: 'Choisir sur la carte',
        geo_pick_hint: 'Touchez la carte, puis déplacez le repère',
        geo_pick_accept: 'Utiliser ce point',
        fill_from_document: 'Remplir depuis une photo ou un PDF',
        fill_reading: 'Lecture…',
        fill_failed: 'Ce document n’a pas pu être lu. Remplissez à la main.',
        fill_nothing: 'Rien n’a pu être lu. Remplissez à la main.',
        fill_check: 'Vérifiez chaque valeur avant d’enregistrer.',
        trash_open: 'Corbeille ({n})',
        trash_viewing:
            'Vous êtes dans la corbeille. Ces enregistrements ne figurent pas dans la liste.',
        trash_back: 'Retour à la liste',
        trash_empty: 'Rien n’a été supprimé ici.',
        trash_restore: 'Restaurer',
        trash_purge: 'Supprimer définitivement',
        trash_purge_title: 'Supprimer définitivement {n} enregistrements ?',
        trash_purge_message: 'Cette fois, il n’y a pas de retour en arrière.',
        trash_restored: '{n} restaurés, {skipped} ignorés.',
        trash_purged: '{n} supprimés définitivement, {skipped} ignorés.',
        relation_trashed: '(supprimé)',
        bulk_delete_dependents:
            '{detail} pointent vers ceux-ci et se retrouveront sans cette donnée.',
        bulk_failed: 'Impossible à appliquer.',
    },
};

/**
 * The keys a language is missing against the English table.
 *
 * Asked this way rather than by comparing VALUES: an abbreviation is often the
 * same string in several languages ("30 d"), and a value-difference check
 * reports those as untranslated while quietly accepting a key that fell back.
 * Mirrors DocWords::missingKeys on the PHP side.
 */
export function missingWordKeys(lang: string): string[] {
    const table = WORDS[lang] ?? {};

    return Object.keys(WORDS.en).filter((key) => !(key in table));
}

/** Every language the runtime claims to speak. */
export function wordLanguages(): string[] {
    return Object.keys(WORDS);
}

/**
 * One phrase, in the app's language, with its placeholders filled.
 *
 * @param locale the APP's locale, not the platform session's
 */
export function runtimeWord(
    locale: string | undefined,
    key: string,
    replace: Record<string, string | number> = {},
): string {
    const lang = (locale ?? 'en').slice(0, 2).toLowerCase();
    let out = WORDS[lang]?.[key] ?? WORDS.en[key] ?? key;

    for (const [token, value] of Object.entries(replace)) {
        out = out.replace(`{${token}}`, String(value));
    }

    return out;
}
